import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/UniversalComponents/header";
import Footer from "@/components/UniversalComponents/footer";
import { inter } from "./fonts";


export const metadata = {
  title: "Chilanga Presbyterian Church",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
      
         
          <Header/>
      
        
        {children}

        <Footer/>
      </body>
    </html>
  );
}
